import { Playfair_Display, Nunito } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import MenuShell from "./components/MenuShell";
import ConditionalFooter from "./components/ConditionalFooter";

const houseMinimalist = localFont({
  src: "./fonts/House Minimalist.otf",
  variable: "--font-house-minimalist",
  display: "swap",
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  display: "swap",
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://res.cloudinary.com" />
        <link rel="dns-prefetch" href="https://res.cloudinary.com" />
      </head>
      <body
        className={`${nunito.variable} ${playfair.variable} ${houseMinimalist.variable} antialiased`}
      >
        <MenuShell />
        {children}
        <ConditionalFooter />
      </body>
    </html>
  );
}
